language: python

version:
  - "3.6"
  - "3.7"

services: sqlite3
install:
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/flask-test"
  - export FLASK_DEBUG=1

script: 
  - echo "haha"
