language: python

version:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coverage

script: true
  - nosetests --with-coverage --coverage report

script:
  - pytest

after_script:
  - coveralls

after_success:
  - codecov
